# cf template declares resources to be created and configured.
# "Resources" is a top level object, at least one is required.
# A Resource object contains attributes and "Type" defines the kind of AWS resource
# Syntax: AWS::<ProductIdentifier>::<ResourceType>
Resources:
  HelloBucket:  # name of resource
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead

# Properties attribute is used to specify the information for the resource.

# Lambda function
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function ListBucketsCommand.
Resources:
  primer:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs18.x
      Role: arn:aws:iam::123456789012:role/lambda-role
      Handler: index.handler
      Code:
        ZipFile: |
          const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
          const s3 = new S3Client({ region: "us-east-1" }); // replace "us-east-1" with your AWS region

          exports.handler = async function(event) {
            const command = new ListBucketsCommand({});
            const response = await s3.send(command);
            return response.Buckets;
          };
      Description: List Amazon S3 buckets in us-east-1.
      TracingConfig:
        Mode: Active