apiVersion: v1
kind: ConfigMap
metadata:
  name: cwagentconfig
data:
  cwagentconfig.json: |
    {
      "agent": {
        "logfile": ""
      },
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/app/log/production.log",
                "log_group_name": "nginx_test",
                "log_stream_name": "{instance_id}",
                "timezone": "UTC",
                "timestamp_format": "%d/%b/%Y:%H:%M:%S"
              }
            ]
          }
        }
      }
    }
