# Generator: List (a literal list with elements, e.g cluster name and ip), Cluster (you ensure that new clusters are defined within argocd cluster list)
# Git Generator: json file in git is edited and generators are updated
#     With generator we can generate parameters to be substituted in applications
#     "The purpose of the Generator is to target argocd applications to clusters and different environments"
# ApplicationSet controller is Used for add-ons and deploying applications to multiple clusters
# Argocd Controller create/update/delete Application resource, 
# takes ApplicationSet resource as input, and outputting one or more Argo CD Application resources
#     Application's k8s resources (deployments, services, configmaps etc) are created by argocd as defined in spec field: parameters from Generator + template = app
# Template fields: 
#     project refers to the Argo CD Project in use (default may be used here to utilize the default Argo CD Project),
#     repoURL: URL of the repository (eg https://github.com/argoproj/argocd-example-apps.git)
#     path: Path within the repository where Kubernetes manifests (and/or Helm, Kustomize, Jsonnet resources) are located
#     destination: Defines which Kubernetes cluster/namespace to deploy to, name: Name of the cluster (within Argo CD) to deploy to
#     server: API Server URL for the cluster, either provide server URL or name of the cluster and not both
# Control how changes are made to applications and their corresponding cluster resources (like deployments, services) by applicationset controller by defining sync policy
# 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
#     - cluster: engineering-prod
#       url: https://kubernetes.default.svc
#       foo: bar
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/applicationset.git
        targetRevision: HEAD
        path: examples/list-generator/guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook